name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - uses: benfrisbie/docker-tag-build-push-action/@main
        with:
          push: ${{ github.event_name == 'push' }}
          username: ${{ github.actor }}
          password: ${{ github.token }}